name: Main Workflow
concurrency:
  group: one-at-time
  cancel-in-progress: false
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16

      - name: Check out the code
        uses: actions/checkout@v2

      - name: Check that files were correctly generated
        run: |
          go generate  ./...
          files=$(git status --porcelain)
          if [[ -n ${files}  ]]; then
            >&2 echo "Go generate resulted in changed files:"
            >&2 echo ""
            >&2 echo "${files}"
            >&2 echo ""
            >&2 echo "Please run \`go generate ./...\` to regenerate code."
            exit 1
          fi

      - name: Check that the packages can be built
        run: go build ./...

      - name: Check for linting errors
        run: make lint

      - name: Run tests
        run: make test
        env:
          AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}

      - name: Update codecov report
        uses: codecov/codecov-action@v2
        with:
          file: coverage.out
          fail_ci_if_error: true
          verbose: true
